FILE_INICIALITZADOR = 0-Inicialitzador

INICIALITZADOR_O_	=			\
	$(INICIALITZADOR_INICIALITZA_O_)	\

INICIALITZADOR_INICIALITZA_C_ = $(FILE_INICIALITZADOR)/inicialitza.c
INICIALITZADOR_INICIALITZA_H_ = $(FILE_INICIALITZADOR)/inicialitza.h
INICIALITZADOR_INICIALITZA_O_ = $(OBJDIR)/inicialitza.o
INICIALITZADOR_INICIALITZA_D_ =	$(INICIALITZADOR_INICIALITZA_C_)	\
