FILE_SINTACTIC = 4-Sintàctic

SINTACTIC_O_		=			\
	$(SINTACTIC_SHUTING_YARD_ALGORITHM_O_)	\

SINTACTIC_SHUTING_YARD_ALGORITHM_C_ = $(FILE_SINTACTIC)/shunting-yard_algorithm.c
SINTACTIC_SHUTING_YARD_ALGORITHM_H_ = $(FILE_SINTACTIC)/shunting-yard_algorithm.h
SINTACTIC_SHUTING_YARD_ALGORITHM_O_ = $(OBJDIR)/shunting-yard_algorithm.o
SINTACTIC_SHUTING_YARD_ALGORITHM_D_ = $(SINTACTIC_SHUTING_YARD_ALGORITHM_C_)	\
	$(SINTACTIC_SHUTING_YARD_ALGORITHM_H_)					\
	$(EXECUTOR_DESCRIPTOR_H_)						\
	$(DEPURADOR_DEPURADOR_H_)						\
	$(UTILS_BASIC_H_)							\
