FILE_EXECUTOR = 1-Executor

EXECUTOR_O_		=			\
	$(EXECUTOR_DESCRIPTOR_O_)		\
	$(EXECUTOR_INSTRUCCIONS_O_)		\

EXECUTOR_DESCRIPTOR_C_ = $(FILE_EXECUTOR)/descriptor.c
EXECUTOR_DESCRIPTOR_H_ = $(FILE_EXECUTOR)/descriptor.h
EXECUTOR_DESCRIPTOR_O_ = $(OBJDIR)/exec_descriptor.o
EXECUTOR_DESCRIPTOR_D_ = $(EXECUTOR_DESCRIPTOR_C_)	\
	$(EXECUTOR_DESCRIPTOR_H_)			\

EXECUTOR_INSTRUCCIONS_C_ = $(FILE_EXECUTOR)/instruccions.c
EXECUTOR_INSTRUCCIONS_H_ = $(FILE_EXECUTOR)/instruccions.h
EXECUTOR_INSTRUCCIONS_O_ = $(OBJDIR)/exec_instruccions.o
EXECUTOR_INSTRUCCIONS_D_ = $(EXECUTOR_INSTRUCCIONS_C_)	\
	$(EXECUTOR_INSTRUCCIONS_H_)			\
	$(EXECUTOR_DESCRIPTOR_H_)			\
